CREATE TABLE IF NOT EXISTS visits (
    id SERIAL PRIMARY KEY,
    visited_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO visits (visited_at) VALUES ('2025-12-02 14:01:00') ON CONFLICT DO NOTHING;
INSERT INTO visits (visited_at) VALUES ('2025-12-02 14:02:00') ON CONFLICT DO NOTHING;